on:
  push:
    branches: [ "*" ]

jobs:
  workflow_1:
    uses: ./.github/workflows/workflow1.yaml

  workflow_2:
    needs: workflow_1
    runs-on: windows-latest
    steps:
      - name: work flow 1 output
        id: wf2step1
        run: > 
          echo ${{ needs.workflow_1.outputs.my_output }}

  workflow_3:
    needs: workflow_1
    uses: ./.github/workflows/workflow3.yaml
    with:
      workflow_1_input: ${{ needs.workflow_1.outputs.my_output }}