on:
  workflow_call:
    outputs:
      myOutput:
        value: ${{ jobs.wf1job1.outputs.myOutput }}

jobs:
  wf1job1:
    runs-on: windows-latest
    outputs:
      myOutput: ${{ steps.wf1step1.outputs.myOutput }}
    steps:
      - name: step 1
        id: wf1step1
        run: > 
          Write-Output "::set-output name=myOutput::hello"
      - name: step 2
        id: wf1step2
        run: > 
          echo ${{ steps.wf1step1.outputs.myOutput}}