on:
  workflow_call:
    outputs:
      my_output:
        value: ${{ jobs.job_1.outputs.my_output }}

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.step_1.outputs.my_output }}
    steps:
      - name: step 1
        id: step_1
        run: > 
          echo "::set-output name=my_output::hello"
      - name: step 2
        id: step_2
        run: > 
          echo ${{ steps.step_1.outputs.my_output}}

          temp='happy-plant-0sd33cd78303.2.azurestaticapps.net'

          temp="http://$temp"
          
          echo $temp