on:
  workflow_call:
    outputs:
      my_output:
        value: ${{ jobs.job_1.outputs.my_output }}

jobs:
  job_1:
    runs-on: windows-latest
    outputs:
      my_output: ${{ steps.step_1.outputs.my_output }}
    steps:
      - name: step 1
        id: step_1
        run: > 
          Write-Output "::set-output name=my_output::hello"
          $temp="afternoon"
          Write-Output "::set-output name=my_output_two::$($temp)"
      - name: step 2
        id: step_2
        run: > 
          echo ${{ steps.step_1.outputs.my_output}}
          echo ${{ steps.step_1.outputs.my_output_two}}